# Generated by Django 3.1.7 on 2021-04-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('measures', '0005_auto_20210420_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='set_measures',
            fields=[
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='Author')),
                ('measure_1_name', models.CharField(max_length=20, verbose_name='measure 1')),
                ('measure_2_name', models.CharField(max_length=20, verbose_name='measure 2')),
                ('measure_3_name', models.CharField(max_length=20, verbose_name='measure 3')),
                ('measure_4_name', models.CharField(max_length=20, verbose_name='measure 4')),
                ('measure_5_name', models.CharField(max_length=20, verbose_name='measure 5')),
                ('measure_6_name', models.CharField(max_length=20, verbose_name='measure 6')),
            ],
        ),
        migrations.DeleteModel(
            name='setmeasures',
        ),
    ]
