# Generated by Django 3.1.7 on 2021-04-20 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measures', '0006_auto_20210420_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='set_measures',
            new_name='measure_names',
        ),
        migrations.RenameModel(
            old_name='measures',
            new_name='measure_values',
        ),
    ]
