# Generated by Django 3.1.7 on 2021-04-27 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measures', '0007_auto_20210420_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure_names',
            name='measure_1_name',
            field=models.CharField(default='', max_length=20, verbose_name='measure 1'),
        ),
        migrations.AlterField(
            model_name='measure_names',
            name='measure_2_name',
            field=models.CharField(default='', max_length=20, verbose_name='measure 2'),
        ),
        migrations.AlterField(
            model_name='measure_names',
            name='measure_3_name',
            field=models.CharField(default='', max_length=20, verbose_name='measure 3'),
        ),
        migrations.AlterField(
            model_name='measure_names',
            name='measure_4_name',
            field=models.CharField(default='', max_length=20, verbose_name='measure 4'),
        ),
        migrations.AlterField(
            model_name='measure_names',
            name='measure_5_name',
            field=models.CharField(default='', max_length=20, verbose_name='measure 5'),
        ),
        migrations.AlterField(
            model_name='measure_names',
            name='measure_6_name',
            field=models.CharField(default='', max_length=20, verbose_name='measure 6'),
        ),
        migrations.AlterField(
            model_name='measure_values',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
