# Generated by Django 3.1.7 on 2021-04-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210426_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_id',
            field=models.CharField(default='facebook', max_length=50, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_id',
            field=models.CharField(default='instagram', max_length=50, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='soundcloud_id',
            field=models.CharField(default='soundcloud', max_length=50, verbose_name='soundcloud'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_id',
            field=models.CharField(default='spotify', max_length=50, verbose_name='spotify'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_id',
            field=models.CharField(default='twitter', max_length=50, verbose_name='twitter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_id',
            field=models.CharField(default='youtube', max_length=50, verbose_name='youtube'),
        ),
    ]
