# Generated by Django 3.1.7 on 2021-04-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210426_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='youtube_id',
            field=models.CharField(default='youtube', max_length=50, verbose_name='youtube'),
        ),
    ]
