# Generated by Django 3.1.7 on 2021-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210426_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(default='interests', max_length=250, verbose_name='interests'),
        ),
    ]
