# Generated by Django 3.1.7 on 2021-05-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210502_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(default='interests', max_length=750, verbose_name='interests'),
        ),
    ]
