# Generated by Django 3.1.7 on 2021-05-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210504_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='email', max_length=100, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='phone', max_length=100, verbose_name='phone'),
        ),
    ]
